nutgram:
  # The Telegram bot token
  token: '%env(string:TELEGRAM_TOKEN)%'

  # Optional shared secret to verify incoming webhook calls (use with $bot->setWebhook(secret: ...))
  #webhook_secret: '%env(string:WEBHOOK_SECRET)%'

  # If the nutgram bundle should automatically load the routes from config/telegram.php
  routes: true

  # Extra or specific configuration
  config: [ ]
